Test_API/Test_API/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Test_API/api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contacto/', views.contacto, name='contacto'),
    path('galeria/', views.galeria, name='galeria'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('user', views.UserView.as_view(), name='user'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

Test_API/api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=150)
    username = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

opc_consultas = [
    [0, "Consulta"],
    [1, "Reclamo"],
    [2, "Sugerencia"],
    [3, "Felicitaciones"]
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opc_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

Test_API/api/forms.py
from django import forms
from . import models

class ContactoForm(forms.ModelForm):
    
    #nombre = forms.CharField(widget=forms.TextInput(attrs={"class":'form-control'}))

    class Meta:
        model = models.Contacto
        #fields = ["nombre", "correo", "tipo_consulta", "mensaje", "avisos"]
        fields = '__all__'

Test_API/api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.exceptions import AuthenticationFailed
from .serializers import UserSerializer
from .models import Producto, User
from .forms import ContactoForm
import jwt, datetime

# Create your views here.
def home(request):
    productos = Producto.objects.all()
    data = {
        'productos': productos
    }
    return render(request, 'home.html', data)

def contacto(request):
    data = {
        'form': ContactoForm()
    }

    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = 'Contacto Guardado'
        else:
            data["form"] = formulario    
    
    return render(request, 'contacto.html', data)

def galeria(request):
    return render(request, 'galeria.html')

class RegisterView(APIView):
    def post(self, request):
        serializer = UserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

class LoginView(APIView):
    def post(self, request):
        email = request.data['email']
        password = request.data['password']

        user = User.objects.filter(email=email).first()

        if user is None:
            raise AuthenticationFailed('User not found!')
        
        if not user.check_password(password):
            raise AuthenticationFailed('Incorrect password!')

        payload = {
            'id': user.id,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=60),
            'iat': datetime.datetime.utcnow()
        }

        token = jwt.encode(payload, 'secret', algorithm='HS256')
        response = Response()

        response.set_cookie(key='jwt', value=token, httponly=True)
        response.data = {
            #'message': 'Success'
            'jwt': token
        }

        return response

class UserView(APIView):
    def get(self, request):
        token = request.COOKIES.get('jwt')

        if not token:
            raise AuthenticationFailed('Unauthenticated!')
        
        try:
            payload = jwt.decode(token, 'secret', algorithms=['HS256'])
        except jwt.ExpiredSignatureError:
            raise AuthenticationFailed('Unauthenticated!')

        user = User.objects.filter(id=payload['id']).first()
        serializer = UserSerializer(user)

        return Response(serializer.data)

class LogoutView(APIView):
    def post(self, request):
        response = Response()
        response.delete_cookie('jwt')
        response.data = {
            'message': 'Success'
        }

        return response

Test_API/templates/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Market</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    {% block css %}
    {% endblock css %}
</head>
<body>

    
    <header id="header">
        <img class="menu" src="{% static 'img/menuiconwhite.png' %}" alt="menu" id="menu">
        <div class="contenedor_logo">
            <img  class="logo"  src="{% static 'img/tecnomarketpngicono.png' %}" alt="logo">
        </div>

        <div>
            
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'home' %}"> Inicio </a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li>
                        <a href="{% url 'galeria' %}">Galería</a>
                    </li>
                    {% if perms.app.add_producto %}
                    <li>
                        <a href="#">Agregar Producto</a>
                    </li>
                    {% endif %}
                    {% if perms.app.view_producto %}
                    <li>
                        <a href="#">Productos</a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'logout' %}">Cerrar Sesión</a>
                    </li>
                    <!--<li>
                        <a href="#">@{{ user.username }}</a>
                    </li>-->
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">Iniciar Sesión</a>
                    </li>
                    <li>
                        <a href="{% url 'register' %}">Registrate</a>
                    </li>
                    {% endif %}

                </ul>
            </nav>

        </div>

    </header>

    <div id="contenido">

        {% block contenido %}
        {% endblock contenido %}

    </div>

    <footer>
        <div class="marcas">
            <img src="{% static 'img/footer/apple.png' %}" alt="apple">
            <img src="{% static 'img/footer/lenovo.png' %}" alt="lenovo">
            <img src="{% static 'img/footer/microsoft.png' %}" alt="microsoft">
            <img src="{% static 'img/footer/samsung.png' %}" alt="samsung">
            <img src="{% static 'img/footer/xiaomi.png' %}" alt="xiaomi">
        </div>
        <div class="logo_footer">
            <img src="{% static 'img/tecnomarketpngicono.png' %}" alt="logo">
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/menu.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                    "title": "Confirmación",
                    "text": "{{m}}",
                    "icon": "success"
                })
            </script>
        {% endfor %}
    {% endif %}

    {% block js %}
    {% endblock js %}
</body>
</html>

Test_API/templates/contacto.html
{% extends 'base.html' %}

{% block contenido %}
{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Contactanos!</h2>
                <hr>
                <form action="" method="post">
        
                    {% csrf_token %}
                
                    {{ form | crispy }}
                    <br>
                    
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    </div>
                
                </form>
                {{mensaje}}
            </div>
        </div>

    </div>
</div>

{% endblock contenido %}

Test_API/templates/galeria.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock css %}

{% block js %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock js %}

{% block contenido %}

<h2>Galería de nuestra tienda</h2>
<br><br>
<div class="galeria">
    <a data-fancybox="gallery" href="{% static 'img/tienda/tienda1.jpg' %}"><img src="{% static 'img/tienda/tienda1.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'img/tienda/tienda2.jpeg' %}"><img src="{% static 'img/tienda/tienda2.jpeg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'img/tienda/tienda3.jpg' %}"><img src="{% static 'img/tienda/tienda3.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'img/tienda/tienda5.jpg' %}"><img src="{% static 'img/tienda/tienda5.jpg' %}"></a>     
    <a data-fancybox="gallery" href="{% static 'img/tienda/tienda4.jpg' %}"><img src="{% static 'img/tienda/tienda4.jpg' %}"></a>
</div>

{% endblock contenido %}

Test_API/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock css %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });
    });
</script>
{% endblock js %}

{% block contenido %}

<div class="slider">
    <div>
        <img src="{% static 'img/banner/banner1.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'img/banner/banner2.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'img/banner/banner3.png' %}" alt="">
    </div>
</div>
{% load humanize %}
<h2>Productos</h2>
<div class="productos">
    {% for p in productos %}
    <div class="producto">

        <div class="contenedor_producto">
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="imagen producto">
            {% endif %}
            <div class="detalle">
                <h5>{{ p.marca | capfirst }}</h5>
                <h2>{{ p.nombre | title }}</h2>
                <h3>${{ p.precio | intcomma }}</h3>
            </div>

        </div>
    
    </div>
    {% endfor %}
</div>

{% endblock contenido %}

Test_API/templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

Test_API/templates/producto/agregar.html
{% extends 'base.html' %}

{% block contenido %}
{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Agregar Producto</h2>

                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}

                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>

                </form>
                {{ mensaje }}
            </div>
        </div>

    </div>
</div>

{% endblock contenido %}

Test_API/templates/producto/listar.html
{% extends 'base.html' %}

{% block js %}
    <script>
        function eliminarProducto(id){
            Swal.fire({
                "title": "¿Estas Seguro?",
                "text": "Esta acción no se puede deshacer",
                "icon": "question",
                "showCancelButton": true,
                "cancelButtonText": "No, Cancelar",
                "confirmButtonText": "Si, Eliminar",
                "confirmButtonColor": "#dc3545"
            })
            .then(function(result){
                if(result.isConfirmed){
                    window.location.href = "eliminar-producto/"+id+"/"
                }
            })
        }
    </script>
{% endblock %}

{% block contenido %}
{% load humanize %}
<br>
<div class="card">
    <div class="card-body">
        <h2>Lista de Productos</h2>
        <hr>
        <table class="table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>¿Es Nuevo?</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
            
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>${{ p.precio | intcomma }}</td>
                <td>{{ p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
                </td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info btn-sm">Editar</a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-danger btn-sm">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
        
            {% endfor %}
        
        </table>

        <div>
            {% include 'paginator.html' %}
        </div>

    </div>
</div>

{% endblock contenido %}

Test_API/templates/producto/modificar.html
{% extends 'base.html' %}

{% block contenido %}
{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Editar Producto</h2>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">

                    {% csrf_token %}
                    {{ form | crispy }}

                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Editar" class="btn btn-primary">
                    </div>

                </form>
                {{ mensaje }}
            </div>
        </div>

    </div>
</div>

{% endblock contenido %}